
version: "3.5"

services:
  phoenix:
    build: .
    volumes:
      - ./src:/app
    ports:
      - "4001:4001"
    depends_on:
      - db
      
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data